services:
  app:
    build: .
    container_name: node_dev
    restart: unless-stopped

    user: root
    working_dir: /home/node/app

    volumes:
      - .:/home/node/app  # só código (sem node_modules!)

    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

    stdin_open: true
    tty: true

    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_db
    restart: unless-stopped

    ports:
      - "1433:1433"

    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=As,k71l!

    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: